# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f60f397a25fbe39fd3fee79f05eba1f5ffe068480bc3bbe6f987c3f88955a5d6ba39e8bdac8c8f6a0d52a8d9df03af617a94c3bd2304ea14a0830809f3bb3ae

test:
  secret_key_base: 60db70e16739d71e8670bf9c28f1ffb4d70bae8b6b7da0670d05d2dfb99bd4a7c5f16e1ce0d69b852375c259555b408c014c158372181cb76613a9f3e8484f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
